Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalRDemo.Controllers
{
    public class ClientController : Controller
    {
        // GET: Client
        public ActionResult ChannelA()
        {
            return View();
        }

        public ActionResult ChannelB()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalRDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HubController.cs
using Microsoft.AspNet.SignalR;
using SignalRDemo.Hubs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalRDemo.Controllers
{
    public class HubController : Controller
    {
        private readonly static IHubContext hub = GlobalHost.ConnectionManager.GetHubContext<ChannelHub>();
        // GET: Hub
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Send(string groupName, string message)
        {
            hub.Clients.Group(groupName).showmessage(message);

            return View("Index");
        }
    }
}

Views/Client/ChannelA.cshtml
@{
    ViewBag.Title = "Channel A";
}

<div class="row">
    <div class="col-md-12 h3">Channel A</div>
    <div class="col-md-12">
        message:<span id="messages"></span>
    </div>
</div>

@section scripts
{
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script>
        $(function () {
            var channelHub = $.connection.channelHub;

            channelHub.client.showmessage = function (message) {
                $('#messages').text(message);
            };

            $.connection.hub.start()
                .done(function () {
                    channelHub.server.addGroup("ChannelA");
                });
        });
    </script>
}

Views/Client/ChannelB.cshtml
@{
    ViewBag.Title = "Channel B";
}

    <div class="row">
        <div class="col-md-12 h3">Channel B</div>
        <div class="col-md-12">
            message:<span id="messages"></span>
        </div>
    </div>

@section scripts
{
    <script src="~/Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <script>
        $(function () {
            var channelHub = $.connection.channelHub;

            channelHub.client.showmessage = function (message) {
                $('#messages').text(message);
            };

            $.connection.hub.start()
                .done(function () {
                    channelHub.server.addGroup("ChannelB");
                });
        });
    </script>
}

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <div>@Html.ActionLink("Server", "Index", "Hub", null, new { target = "_blank" })</div>
        <div>@Html.ActionLink("Channel A", "ChannelA", "Client", null, new { target = "_blank" })</div>
        <div>@Html.ActionLink("Channel B", "ChannelB", "Client", null, new { target = "_blank" })</div>
    </div>
</div>

Views/Hub/Index.cshtml
@{
    ViewBag.Title = "Hub";
}

<div class="row">
    <div class="col-md-12">
        <form method="post" action="/Hub/Send">
            <div class="form-group">
                <label for="groupName">頻道</label>
                <select class="form-control" id="groupName" name="groupName">
                    <option value="ChannelA">Channel A</option>
                    <option value="ChannelB">Channel B</option>
                </select>
            </div>
            <div class="form-group">
                <label for="message">訊息</label>
                <input type="text" class="form-control" id="message" name="message">
            </div>
            <button type="submit" class="btn btn-primary">傳送</button>
        </form>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>